myapp/urls.py
from django.urls import path
from myapp import views


app_name = "myapp"

urlpatterns = [
    path(r"", views.index, name="index"),
    path(r"<int:book_id>", views.details, name="details"),
    path(r"about/", views.about, name="about"),
    path("feedback/", views.getFeedback, name="feedback1"),
    path("findbooks/", views.findbooks, name="findbooks"),
    path("place_order", views.place_order, name="place_order"),
    path("review/", views.review_view, name="review"),
    path("login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("chk_reviews/<int:book_id>/", views.chk_reviews, name="chk_reviews"),
]

mysiteS24/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'myapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'myapp/', include('myapp.urls1')),
    path(r'myapp/', include('myapp.urls')),

]

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=50, default="USA")


class Book(models.Model):
    CATEGORY_CHOICES = [
        ("S", "Scinece&Tech"),
        ("F", "Fiction"),
        ("B", "Biography"),
        ("T", "Travel"),
        ("O", "Other"),
    ]
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default="S")
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    publisher = models.ForeignKey(
        Publisher, related_name="books", on_delete=models.CASCADE
    )
    description = models.TextField(blank=True, null=True)
    num_reviews = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title + " " + self.category + " " + self.get_category_display()


# Lab4
class Member(User):
    STATUS_CHOICES = [
        (1, "Regular member"),
        (2, "Premium Member"),
        (3, "Guest Member"),
    ]

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300, blank=True, null=True)
    city = models.CharField(max_length=20, default="Windsor")
    province = models.CharField(max_length=2, default="ON")
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True)


class Order(models.Model):
    ORDER_VALUE_CHOICES = [
        (0, "Purchase"),
        (1, "Borrow"),
    ]
    books = models.ManyToManyField(Book)
    member = models.ForeignKey(Member, related_name="orders", on_delete=models.CASCADE)
    order_type = models.IntegerField(choices=ORDER_VALUE_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)
    def total_items(self):
        return self.books.count()
    total_items.short_description = 'Total Books'

class Review(models.Model):
    reviewer = models.EmailField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True, null=True)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.reviewer} - {self.book.title} ({self.rating}/5)"

myapp/forms.py
from django import forms
from django.forms.widgets import RadioSelect
from .models import *

class FeedbackForm(forms.Form):
    FEEDBACK_CHOICES = [
        ('B', 'Borrow'),
        ('P', 'Purchase'),
    ]
    feedback = forms.ChoiceField(choices = FEEDBACK_CHOICES)

class SearchForm(forms.Form):
    name = forms.CharField(required=False, label='Your Name')
    category = forms.ChoiceField(
        required=False,
        choices=Book.CATEGORY_CHOICES,
        label='Select a category:',
        widget=RadioSelect
    )
    max_price = forms.IntegerField(label='Maximum Price', min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['books', 'member', 'order_type']
        widgets = {'books': forms.CheckboxSelectMultiple(), 'order_type':forms.RadioSelect}
        labels = {'member': u'Member name', }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'book', 'rating',  'comments']
        widgets = {'books': forms.RadioSelect()}
        labels = {'reviewer' : 'Please enter a valid email' , 'rating' : 'Rating: An integer between 1 (worst) and 5 (best)'}

myapp/views.py
# Create your views here.
from django.shortcuts import render, redirect

from myapp.models import Book
from django.http import HttpResponse
from .forms import *
from .models import Book
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
import random


def index(request):
    last_login = request.session.get("last_login")
    if last_login:
        message = f"Your last login was at {last_login}"
    else:
        message = "Your last login was more than one hour ago"
    booklist = Book.objects.all().order_by("id")[:10]
    return render(
        request, "myapp/index.html", {"booklist": booklist, "message": message}
    )


def details(request, book_id):
    book = Book.objects.get(pk=book_id)
    return render(request, "myapp/details.html", {"book": book})


def about(request):
    lucky_num = request.COOKIES.get("lucky_num")
    if lucky_num:
        mynum = lucky_num
    else:
        mynum = random.randint(1, 100)
        response = render(request, "myapp/about.html", {"mynum": mynum})
        response.set_cookie("lucky_num", mynum, max_age=5 * 60)  # Expires in 5 minutes
        return response
    return render(request, "myapp/about.html", {"mynum": mynum})


def getFeedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback_choices = form.cleaned_data["feedback"]
            choices_text = []
            for choice in feedback_choices:
                if choice == "B":
                    choices_text.append(" to borrow books.")
                elif choice == "P":
                    choices_text.append(" to purchase books.")
                else:
                    choices_text.append(" None.")
            return render(
                request, "myapp/fb_results.html", {"choices_text": choices_text}
            )
        else:
            return HttpResponse("Invalid data")
    else:
        form = FeedbackForm()
        return render(request, "myapp/feedback.html", {"form": form})


def get_category_name(category_id):
    for id, name in Book.CATEGORY_CHOICES:
        if id == category_id:
            return name
    return None  # or raise an exception if you prefer


def findbooks(request):

    if request.method == "POST":
        form = SearchForm(request.POST)  # No need to pass category_choices here
        if form.is_valid():
            name = form.cleaned_data.get("name", "")
            category_id = form.cleaned_data.get("category", None)
            print(category_id)
            max_price = form.cleaned_data["max_price"]

            if category_id:
                # Retrieve books for the selected category and max_price
                booklist = Book.objects.filter(
                    category=category_id, price__lte=max_price
                )
            else:
                # Retrieve all books with price <= max_price
                booklist = Book.objects.filter(price__lte=max_price)
            category = get_category_name(category_id)
            print(category)
            if not category_id:
                category = category_id
            # print(booklist)
            return render(
                request,
                "myapp/results.html",
                {
                    "name": name,
                    "category_id": category_id,
                    "booklist": booklist,
                    "category": category,
                },
            )
        else:
            return render(
                request,
                "myapp/findbooks.html",
                {"form": form, "message": "Invalid data"},
            )
    else:
        form = SearchForm()  # Create a blank form
        # form.fields['category'].choices = categories  # Set choices dynamically
        return render(request, "myapp/findbooks.html", {"form": form})


def place_order(request):
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            books = form.cleaned_data["books"]
            order = form.save(commit=False)
            member = order.member
            type = order.order_type
            order.save()
            order.books.set(books)
            if type == 1:
                for b in order.books.all():
                    member.borrowed_books.add(b)
            return render(
                request, "myapp/order_response.html", {"books": books, "order": order}
            )
        else:
            return render(request, "myapp/placeorder.html", {"form": form})

    else:
        form = OrderForm()
        return render(request, "myapp/placeorder.html", {"form": form})


def review_view(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data["rating"]
            if 1 <= rating <= 5:
                review = form.save()
                book = review.book
                book.num_reviews = book.num_reviews + 1
                book.save()
                return redirect("myapp:index")
            else:
                form.add_error("rating", "You must enter a rating between 1 and 5!")
    else:
        form = ReviewForm()
    return render(request, "myapp/review.html", {"form": form})


def user_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session["last_login"] = str(timezone.now())
                request.session.set_expiry(3600)  # Session expires in 1 hour
                return HttpResponseRedirect(reverse("myapp:index"))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            return HttpResponse("Invalid login details.")
    else:
        return render(request, "myapp/login.html")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("myapp:index"))


@login_required
def chk_reviews(request, book_id):
    user = request.user
    # Check if the user is a member
    if Member.objects.filter(id=user.id).exists():
        try:
            book = Book.objects.get(pk=book_id)
            reviews = Review.objects.filter(book=book)
            if reviews.exists():
                avg_rating = reviews.aggregate(Avg("rating"))["rating__avg"]
                return render(
                    request,
                    "myapp/chk_reviews.html",
                    {"avg_rating": avg_rating, "book": book},
                )
            else:
                return render(
                    request,
                    "myapp/chk_reviews.html",
                    {"message": "No reviews submitted for this book."},
                )
        except Book.DoesNotExist:
            return render(
                request, "myapp/chk_reviews.html", {"message": "Book not found."}
            )
    else:
        return render(
            request,
            "myapp/chk_reviews.html",
            {"message": "You are not a registered member!"},
        )

templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}
eBook APP About page
{% endblock %}

{% block body_block %}
<p>This is an ebook app.</p>
<p>Your lucky number is: {{ mynum }}</p>
{% endblock %}

templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>eBook App</title>
</head>
<body>
<p> This is an eBook APP</p>
<p><a href="{% url 'myapp:index' %}">Home page</a></p>

</body>
</html>

templates/myapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style1.css' %}" />
        <title>eBook APP - {% block title %}Welcome!{% endblock %}</title>
    </head>

    <body>
        <div>
            <h1>{% block myhdg %}Hello User {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>
                <li class="hbar1"><a href="/myapp/findbooks/">Find Books</a></li>
                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
                <li class="hbar1"><a href = "{% url 'myapp:place_order' %}">Click here to return to place order</a><br/></li>

            </ul>
        </div>
    </body>
</html>

templates/myapp/chk_reviews.html
{% extends "myapp/base.html" %}

{% block title %}Check Reviews{% endblock %}

{% block myhdg %}Check Reviews{% endblock %}

{% block body_block %}
{% if avg_rating %}
<p>Average Rating for {{ book.title }}: {{ avg_rating }}</p>
{% elif message %}
<p>{{ message }}</p>
{% endif %}
{% endblock %}

templates/myapp/details.html
{% extends 'myapp/base.html' %}

{% block title %}
    Book Details
{% endblock %}

{% block body_block %}
    <h1> Details page </h1>
    {% if book and book.title %}
        <h2>Book Information</h2>
        <table>
        <tbody>
        <tr>
            <td>Book Name</td>
            <td>Book Price</td>
            <td>Publishers</td>
        </tr>
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.publisher.name }}</td>
        </tr>

    </tbody>
    </table>

    {% else %}
        <strong>There are no available books with this id!</strong>
    {% endif %}
{% endblock %}

templates/myapp/fb_results.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h1>Selected Feedback Choices:</h1>
    <ul>
        {% for choice_text in choices_text %}
            <li>{{ choice_text }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/myapp/feedback.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:feedback1' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit2" value="Done" />
    </form>

{% endblock %}

templates/myapp/findbooks.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:findbooks' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Search Now" />
    </form>

{% endblock %}

templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
Hello Hayden
{% endblock %}

{% block body_block %}
<p>{{ message }}</p>

{% if booklist %}
<h2>List of Books</h2>
<ol>
    {% for book in booklist %}
    <li>
        <a href="{% url 'myapp:details' book_id=book.id %}">{{ book.title }}</a>
    </li>
    {% endfor %}
</ol>
{% else %}
<strong>There are no available books!</strong>
{% endif %}

{% endblock %}

templates/myapp/index0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>eBook App</title>
</head>
<body>

    {% if booklist %}
        <h2>List of Books</h2>
        <ol>
            {% for book  in booklist %}
                <li> {{book.title}} </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}
<p><a href="{% url 'myapp:about' %}">About page</a></p>
</body>

</html>

templates/myapp/login.html
{% extends "myapp/base.html" %}

{% block title %}Login{% endblock %}

{% block myhdg %}Login{% endblock %}

{% block body_block %}
<form method="post" action="{% url 'myapp:user_login' %}">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>
    <button type="submit">Login</button>
</form>
{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h1> Details page </h1>
    {% if books%}
        <h2>Order Response</h2>
        <table>
        <tbody>
        <tr>
            <td><h2>Book Name</h2></td>
        </tr>
        {% for book in books %}
        <tr>
            <td>{{ book.title }}</td>
        </tr>

        {% endfor %}
    </tbody>
    </table>

    {% else %}
        <strong>There are no available books with this id!</strong>
    {% endif %}
{% endblock %}

templates/myapp/results.html
{% extends 'myapp/base.html' %}
{% block myhdg %}
    Hello {{ name }}
{% endblock %}

{% block body_block %}
    {% if booklist %}
        <h2>List of Books of the following category : {{ category }}</h2>
        <ol>
            {% for book  in booklist %}
                <li > <a href="{% url 'myapp:details' book_id=book.id %}"> {{book.title}} </a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}

{% endblock %}

templates/myapp/review.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<form action="{% url 'myapp:review' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="submit" value="Submit" />
</form>
{% endblock %}